blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/ajnart/dcm/discussions/new?category=feature-suggestion
    about: In order to submit an idea you must create a discussion so that other people can upvote it, quickly showing interest
  - name: Ask a Question
    url: https://github.com/ajnart/dcm/discussions/new?category=q-a
    about: Ask the community for help 
